---
abstract: 'Collection of modules for ExtJS'
author:
  - 'Moritz Onken <onken@netcubed.de>'
generated_by: 'Dist::Zilla version 1.093400'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-ExtJS
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0.29
  Catalyst::Request::REST::ForBrowsers: 0
  Catalyst::Runtime: 5.8
  Catalyst::View::TT: 0
  Config::Any: 0.17
  DBIx::Class: 0
  HTML::Entities: 0
  HTML::FormFu::ExtJS: 0.075
  HTML::FormFu::Model::DBIC: 0
  JSON: 0
  Lingua::EN::Inflect: 0
  Path::Class: 0
  Test::More: 0.92
  Test::WWW::Mechanize::Catalyst: 0
resources:
  repository: http://github.com/monken/catalystx-extjs
version: 0.10
