---
abstract: 'Collection of modules for ExtJS'
author:
  - 'Moritz Onken <onken@netcubed.de>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::WWW::Mechanize::Catalyst: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: BSD
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-ExtJS
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Request::REST::ForBrowsers: 0
  Catalyst::Runtime: 5.8
  Catalyst::View::TT: 0
  Config::Any: 0.17
  DBIx::Class: 0
  HTML::Entities: 0
  HTML::FormFu::ExtJS: 0.07
  HTML::FormFu::Model::DBIC: 0
  JSON: 0
  Lingua::EN::Inflect: 0
  Path::Class: 0
resources:
  license: http://opensource.org/licenses/bsd-license.php
version: 0.08
